steps:
  # Step 1: Install dependencies
  # Menggunakan image resmi Node.js versi 20 dari Docker Hub
  - name: "node:20" # Perubahan di sini!
    entrypoint: bash
    args:
      - -c
      - |
        # Memeriksa apakah node_modules sudah ada di cache volume
        if [ ! -d "/root/.npm/node_modules" ]; then
          echo "Installing dependencies..."
          npm ci --cache /root/.npm --prefer-offline # npm ci untuk install bersih
        else
          echo "Skipping npm install, node_modules found in cache."
        fi
    dir: "." # Jalankan dari direktori root proyek
    volumes:
      - name: "npm-cache" # Mendefinisikan volume cache
        path: /root/.npm

  # Step 2: Build frontend Next.js
  # Menggunakan image resmi Node.js versi 20 yang sama
  - name: "node:20" # Perubahan di sini!
    entrypoint: bash
    args:
      - -c
      - |
        echo "Building Next.js app..."
        npm run build # Jalankan skrip build Next.js Anda
        echo "Build completed. Checking .next folder:"
        ls -la .next/ # Periksa konten direktori .next
    dir: "."
    volumes:
      - name: "npm-cache" # Menggunakan volume cache yang sama
        path: /root/.npm
    env:
      - 'NODE_ENV=production'
      # Tambahkan variabel lingkungan NEXT_PUBLIC_* Anda di sini jika ada
      # Contoh: - 'NEXT_PUBLIC_BACKEND_URL=https://surat-backend-service-140099475583.us-central1.run.app/api'

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "app"
      - "deploy"
      - "--quiet"
    dir: "."

options:
  logging: CLOUD_LOGGING_ONLY
